// Package envfile provides utilities for parsing, manipulating, and writing
// .env files.
//
// # Cast
//
// The Cast function coerces env entry values to canonical string
// representations of a target type. This is useful when .env files are
// generated by different tools that may format the same logical value
// differently (e.g. "TRUE" vs "true", "08080" vs "8080", "3.14000" vs "3.14").
//
// Supported target types:
//
//   - CastString — value is returned unchanged.
//   - CastInt    — value is parsed as a base-8/10/16 integer and re-serialised
//     in base-10 (strips leading zeros).
//   - CastFloat  — value is parsed as a 64-bit float and re-serialised without
//     trailing zeros.
//   - CastBool   — value is parsed by strconv.ParseBool (accepts 1, t, T,
//     TRUE, true, True, 0, f, F, FALSE, false, False) and re-serialised as
//     "true" or "false".
//
// When Strict is true (the default), the first coercion error causes Cast to
// return immediately. When Strict is false, entries that fail coercion keep
// their original value and the error is recorded in the returned CastResult
// slice.
package envfile
